version: '3'

services:
  php-fpm:
    build:
      context: ./docker/php-fpm
    environment:
      - DOCKER_ENVIRONMENT=true
      - APP_SECRET=${APP_SECRET}
      - PHP_IDE_CONFIG=serverName=Docker
    volumes:
      - ./:/var/www
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    ports:
      - "16880:80"
      - "16843:443"
  db:
    image: mysql:latest
    volumes:
      - "./mysql:/var/lib/mysql"
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_USER=test
      - MYSQL_DATABASE=mydb

